### ISSUE TITLE
M1 - Use Case Descriptions

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2101-2201-P3-Team1#17]

**Comment by rawsashimi1604** [comment]
added priority into each use case description

**Comment by rawsashimi1604** [comment]
I worked on use case 1, 2, 3, 4


![Image](https://user-images.githubusercontent.com/75880261/191995409-62840d01-ba5e-44fa-aa69-74581fe3c3bc.png)

**Comment by jibai-kia** [comment]
I work on UC 9 - 12

![Image](https://user-images.githubusercontent.com/90103591/191995970-cb4217ab-9d05-44a8-b7cb-bd3723973e0e.png)

**Comment by irfaan96** [comment]
Worked on use case 5, 6, 7, 8

![Image](https://user-images.githubusercontent.com/33274365/191996117-5e09a552-80bf-476c-945a-e66a57b612f1.png)

**Comment by Christabellet** [comment]
I worked on use case 13,14,15

![Image](https://user-images.githubusercontent.com/94042374/191997759-fece33cf-9358-4a1f-b5d9-14fca4473c0e.png)
