### ISSUE TITLE
M1 - Software Estimation

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2101-2201-P3-Team1#18]

**Comment by rawsashimi1604** [comment]
Link to excel sheet: https://docs.google.com/spreadsheets/d/1Gr_lC7btT4fv4Q5Nr7nnXcsy4P3BDq_TMn_MWyG1UxU/edit#gid=1002197552

**Comment by Christabellet** [comment]
![Image](https://user-images.githubusercontent.com/94042374/192009432-40956912-8352-4ff3-95e7-af7e02400f89.png)
![Image](https://user-images.githubusercontent.com/94042374/192009429-ad5ab239-6b7b-48d1-95ce-47f2727de617.png)
![Image](https://user-images.githubusercontent.com/94042374/192009430-088bfb68-a2b9-4f09-ad76-3381026cf110.png)
![Image](https://user-images.githubusercontent.com/94042374/192009431-dd3bc1ef-ac04-4d38-b0e1-44ff98f98035.png)
