### ISSUE TITLE
M1 - Individual Members Task Reflections

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2101-2201-P3-Team1#19]
All members have written their own tasks reflection.

**Comment by rawsashimi1604** [comment]
Finished up my task reflection

**Comment by rawsashimi1604** [comment]
![Image](https://user-images.githubusercontent.com/75880261/191936384-5ba71115-3950-4d47-a187-0e76b1a2f217.png)

**Comment by irfaan96** [comment]
![Image](https://user-images.githubusercontent.com/33274365/191992075-090331d4-0840-4dd2-883e-b01853ebdfa7.png)

Done with my reflection

**Comment by jibai-kia** [comment]
![Image](https://user-images.githubusercontent.com/90103591/191994565-9428d8d2-145f-4cdb-98fe-81a9efa1660f.png)

**Comment by Christabellet** [comment]
Done with my reflection

![Image](https://user-images.githubusercontent.com/94042374/191998299-a346bdfc-6bdb-454e-bea3-95060cbfc16b.png)
