### ISSUE TITLE
M1 - User Interface Requirements

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2101-2201-P3-Team1#22]

**Comment by jibai-kia** [comment]
![Image](https://user-images.githubusercontent.com/90103591/191641948-47150c16-9a7e-494d-bf53-10d80b9bf34b.png)
![Image](https://user-images.githubusercontent.com/90103591/191641945-008611e7-f1fa-404c-a05f-c2390bf43c35.png)
![Image](https://user-images.githubusercontent.com/90103591/191641946-c75d6cc3-a5e7-4f2f-8dfb-fbb033f4d603.png)
![Image](https://user-images.githubusercontent.com/90103591/191641947-309947e7-dfa5-4fc6-adfb-215dea97bc8e.png)
![Image](https://user-images.githubusercontent.com/90103591/191641950-869d0d93-fe1a-487b-a223-adf00cbe5d2b.png)
![Image](https://user-images.githubusercontent.com/90103591/191641952-7e0d042f-def5-41be-b5e3-8041bfa5b262.png)
![Image](https://user-images.githubusercontent.com/90103591/191641953-340d94c6-06ad-4b4a-b799-b5d845f97f58.png)
![Image](https://user-images.githubusercontent.com/90103591/191641951-cabd7080-4d55-4b99-9715-825d14f91b0c.png)
![Image](https://user-images.githubusercontent.com/90103591/191641949-87f499b0-763f-4e29-8450-0d83fc326eb1.png)

**Comment by irfaan96** [comment]
![Image](https://user-images.githubusercontent.com/33274365/191978381-14cc5cdf-f545-4e6b-8b7e-e83d5d9eddeb.png)

Hi guys have added the UI Requirements. Please look through and feedback.
