### ISSUE TITLE
M1 - Data Dictionary

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2101-2201-P3-Team1#31]

**Comment by jibai-kia** [comment]
I added some that I can think of



![Image](https://user-images.githubusercontent.com/90103591/191997793-46d33bef-2fcc-4406-9ec6-c0aa78aca66c.png)

**Comment by irfaan96** [comment]
Added a few more to the table

![Image](https://user-images.githubusercontent.com/33274365/191998199-5472ca39-fbf7-418f-9f00-65555e3393e8.png)
