### ISSUE TITLE
Lab 5 - Exercises

### ISSUE THREAD

**Issue by jibai-kia** [rawsashimi1604/ICT2101-2201-P3-Team1#39]

**Comment by irfaan96** [comment]
Q1
![image](https://user-images.githubusercontent.com/33274365/193962621-e6c473b4-2529-4f8c-8249-04a56ee9da41.png)

**Comment by irfaan96** [comment]
Q2
![image](https://user-images.githubusercontent.com/33274365/193963493-22c9772e-0be9-4c11-9f03-2bffe9e40c6d.png)
