### ISSUE TITLE
M2 - Specific Requirements

### ISSUE THREAD

**Issue by irfaan96** [rawsashimi1604/ICT2101-2201-P3-Team1#41]

**Comment by rawsashimi1604** [comment]
Updated Use Case Model
![Image](https://user-images.githubusercontent.com/75880261/195321023-d7b54855-a4ef-4da5-b31e-175c020d90e2.png)

**Comment by jibai-kia** [comment]
Updated some of the specific requirements
![Image](https://user-images.githubusercontent.com/90103591/197247915-0cba554e-b1f7-40b6-a02f-ae3781171543.png)
