### ISSUE TITLE
M2 - Software Design

### ISSUE THREAD

**Issue by irfaan96** [rawsashimi1604/ICT2101-2201-P3-Team1#42]

**Comment by jibai-kia** [comment]
Here is our explanation for our chosen Architectural Design and Software Design Patterns.

![Image](https://user-images.githubusercontent.com/90103591/198837549-40d2b062-b17c-4291-82dc-c56fc439df69.png)

Here is our Architectural Methodology

![Image](https://user-images.githubusercontent.com/90103591/198837616-028e7fa0-ca24-4c63-adc7-7632de4118ad.png)
