### ISSUE TITLE
M2 - Project Plan

### ISSUE THREAD

**Issue by irfaan96** [rawsashimi1604/ICT2101-2201-P3-Team1#43]

**Comment by jibai-kia** [comment]
Use Case Weight Table added.

![Image](https://user-images.githubusercontent.com/90103591/198826274-ff73e6f8-0b33-4e64-a633-27090f1e7049.png)

Actor Weight Table added.

![Image](https://user-images.githubusercontent.com/90103591/198826283-39805b4d-cdf9-4b13-88be-46ae2794b4b3.png)

Technical Complexity Factors Table added.

![Image](https://user-images.githubusercontent.com/90103591/198826290-d4b22ef0-491a-4bed-84b1-6d46cce44ed4.png)

Environment Factors Table added.

![Image](https://user-images.githubusercontent.com/90103591/198826295-65ac8c3d-2115-4c0e-9d1d-d63ef0f772f2.png)

Calculation and Explanation added.

![Image](https://user-images.githubusercontent.com/90103591/198826302-96e1e532-5096-4f87-a39f-224e5bc7d066.png)
