### ISSUE TITLE
M2 - Individual Reflections

### ISSUE THREAD

**Issue by irfaan96** [rawsashimi1604/ICT2101-2201-P3-Team1#44]
All group members has added their reflections

**Comment by jibai-kia** [comment]
Reflection added.



![Image](https://user-images.githubusercontent.com/90103591/198840506-86a99e4f-43f4-4b49-981b-c79c364d28cc.png)

**Comment by irfaan96** [comment]
Added my reflection

![Image](https://user-images.githubusercontent.com/33274365/198841186-b875c96f-3475-44fc-94d5-43d84b8d801e.png)

**Comment by rawsashimi1604** [comment]
added my reflection

all reflections done
![Image](https://user-images.githubusercontent.com/75880261/198841297-d03f22c8-b72d-45c0-9e3c-cb78826d39d0.png)

**Comment by Christabellet** [comment]
![Image](https://user-images.githubusercontent.com/94042374/198841450-b1baad53-4c8b-485f-bd62-8ce240b1ef11.png)

Added my reflection
