### ISSUE TITLE
M2 - Updated Use Case Descriptions

### ISSUE THREAD

**Issue by irfaan96** [rawsashimi1604/ICT2101-2201-P3-Team1#45]

**Comment by jibai-kia** [comment]
Here are the updated UC 1 - 17

![Image](https://user-images.githubusercontent.com/90103591/197248321-ee6a965a-724e-4adf-a67f-a34bfa08a790.png)



![Image](https://user-images.githubusercontent.com/90103591/197248365-4830799b-a035-4a20-acbf-96c767748808.png)



![Image](https://user-images.githubusercontent.com/90103591/197248393-65bfb7f9-0231-4432-887c-06d10b3f1960.png)



![Image](https://user-images.githubusercontent.com/90103591/197248433-e44cc1c3-7c4c-4268-aa7f-576b88d1e53b.png)



![Image](https://user-images.githubusercontent.com/90103591/198828633-1c202467-6273-4a28-8053-cf322d16081f.png)



![Image](https://user-images.githubusercontent.com/90103591/198828654-46bb2b1f-126d-4260-b325-bdba84809b27.png)



![Image](https://user-images.githubusercontent.com/90103591/198828694-4db9d475-28ae-4057-8914-a77449a11ce6.png)



![Image](https://user-images.githubusercontent.com/90103591/198828713-c0d7adea-c1c6-4641-8a9d-a3e70064557a.png)



![Image](https://user-images.githubusercontent.com/90103591/198828725-d39809bd-3bea-4bf4-b5b7-2a6173334944.png)



![Image](https://user-images.githubusercontent.com/90103591/198828736-34f95e97-7c4e-44d4-a38e-cd1fb1bc08ae.png)



![Image](https://user-images.githubusercontent.com/90103591/198828750-83a57f58-b2a7-4d35-97a9-edb24116781f.png)



![Image](https://user-images.githubusercontent.com/90103591/198828780-f0c3c6fa-a166-4760-949e-65c4504db85b.png)



![Image](https://user-images.githubusercontent.com/90103591/198828771-663a2eff-fc7f-4656-9bac-30f80cc1f23c.png)



![Image](https://user-images.githubusercontent.com/90103591/198828802-d770c8ad-f9cd-4067-ae9c-26b07d005be0.png)



![Image](https://user-images.githubusercontent.com/90103591/198828815-755d946a-2546-432e-b0ce-477966f74a55.png)



![Image](https://user-images.githubusercontent.com/90103591/198828829-0a4d6274-0316-4445-96fa-7c3db1584d6b.png)
