### ISSUE TITLE
M3 - Figma Hi-Fi prototype

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2101-2201-P3-Team1#48]
## Figma Hi-Fi prototype for M3
Develop prototype and prototype video showcasing the TOMS application for M3

Start Date: 30/10/2022
End Date: 26/11/2022

### Preconditions:
- Wireframes are completed
- Requirements are completed

### Definition of done:
- [x] Prototype Figma Design completed, all features are covered based on the requirement specs
- [x] Prototype video completed (Maximum 3 minutes)
- [x] Added to the report.

**Comment by jibai-kia** [comment]
Figma Hi-Fi prototype overview. Our Figma Hi-Fi prototype link --> https://www.figma.com/file/28vmp3phW34uf40dKpSTyR/2101-prototypes?node-id=0%3A1&t=DTmXuWxkrZjd02bE-1

![Image](https://user-images.githubusercontent.com/90103591/203057152-5973067f-f040-4f73-81a0-6ee16703d499.png)

**Comment by jibai-kia** [comment]
‎

**Comment by jibai-kia** [comment]
‎

**Comment by irfaan96** [comment]
Prototype video is uploaded to YouTube: https://youtu.be/nXuDMSXQkWA
