### ISSUE TITLE
M1 - Prototype for Client Meeting

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2101-2201-P3-Team1#5]

**Comment by jibai-kia** [comment]
https://marvelapp.com/prototype/184g3439

**Comment by Christabellet** [comment]
![Image](https://user-images.githubusercontent.com/94042374/192007794-6f250cd4-7e3b-4926-aa6a-b7a5f3bb1e8c.png)



![Image](https://user-images.githubusercontent.com/94042374/192008163-09858a73-aa5a-48d0-a227-c95d12ac130e.png)
![Image](https://user-images.githubusercontent.com/94042374/192008160-b183533c-8a82-46e1-92f6-1db798fb4939.png)
![Image](https://user-images.githubusercontent.com/94042374/192008159-dd38ce90-b394-4397-8769-c7ae81cc9384.png)
![Image](https://user-images.githubusercontent.com/94042374/192008162-a6c45f04-a250-4a6f-ada3-d932e3d90e70.png)
![Image](https://user-images.githubusercontent.com/94042374/192008161-f68f9193-7e0f-48ca-b24c-b84221d25f94.png)
![Image](https://user-images.githubusercontent.com/94042374/192008165-941347bb-7143-4ac6-b83d-4b23f860bd4e.png)
![Image](https://user-images.githubusercontent.com/94042374/192008158-4dadb1d0-a319-4284-bfed-ada5d14d61d4.png)
![Image](https://user-images.githubusercontent.com/94042374/192008168-da1813fe-c784-4845-ac6f-815eb7942dde.png)
![Image](https://user-images.githubusercontent.com/94042374/192008164-1cec5dec-d639-4085-a4f4-afc785b80e41.png)
