### ISSUE TITLE
M2 - High Level Component Diagram

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2101-2201-P3-Team1#52]

**Comment by jibai-kia** [comment]
Here is the High Level Component Diagram.

![Image](https://user-images.githubusercontent.com/90103591/198557332-784791c8-cff3-48c9-b36a-d58ef352467d.png)

**Comment by rawsashimi1604** [comment]
Needs to be edited to fit new low level component diagram

**Comment by jibai-kia** [comment]
Updated the new low level component diagram






![Image](https://user-images.githubusercontent.com/90103591/198823635-2667635a-0c29-453c-942e-de3390d4b89e.png)
