### ISSUE TITLE
M1 - Meeting Minutes

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2101-2201-P3-Team1#6]
Recording: Yong Chong
Minutes: Christabelle

![Image](https://user-images.githubusercontent.com/90103591/190304133-5b38a121-108e-47cb-b338-9b81fd93af6e.jpeg)

**Comment by Christabellet** [comment]
Client Meeting Minutes 15 Sep 2022

Constraint for scheduling: 
Type of train, routes
No staff is fixed to any train
There are no fixed train type

Reason for a 1 week bandwidth 
- to prevent excessive switching 

Relevant Information Displayed
- Choice given to developers as per their own discretion

Backup Informal system 
Unallocated employees are on standby
- Paid extra as they are on standby
Environment: Employees are being paid basic pay 
- they will be willing to work more to earn extra cash 

Employee Skillsets
- They are individuals with a specialised skillset
- Can only take on jobs within their skillsets

Min/Max working hours
- Client would like to keep it to 40 hrs without having to pay the staff extra for OT.
Top 3 Workers feature is prioritised by client
 - as a quick decision making tool 

Rejection feature
- just as a backup, not urgent 
Type of valid reasons can be a point for improvement

Staff Account not linked to HR System
Context of Why Account creation not linked 
- Not comfortable w PDPA
Can potentially linked to payroll and HR System
Link to expandability. 

Manager stated
- just admin purely for scheduling.
- Negotiate timing w the other places.

General direction
- Client encourage implementing more efficient processes

Goal Of Scheduling
- Minimise the time taken needed to plan the scheduling
