### ISSUE TITLE
M3 - White Box Testing

### ISSUE THREAD

**Issue by Christabellet** [rawsashimi1604/ICT2101-2201-P3-Team1#80]
## Complete White Box Testing for M3

Start Date: 21/11/2022
End Date: 26/11/2022

### Preconditions:
- None

### Definition of done:
- [x] Pseudocode is completed.
- [x] CFG diagram is completed.
- [x] Complexity Calculation is completed 
- [x] All Basis Paths are completed.
- [x] Test cases are completed.
- [x] Added to the report.

**Comment by Christabellet** [comment]
CFG Diagram Completed

![Image](https://user-images.githubusercontent.com/94042374/203083593-94cfe10e-9728-4510-b752-8cddda7e83be.png)

**Comment by Christabellet** [comment]
All basis paths are completed

![Image](https://user-images.githubusercontent.com/94042374/203083863-7c575f7b-0307-4876-87cd-66b1f3fd9e68.png)

**Comment by Christabellet** [comment]
Cyclomatic Complexity Calculation completed

![Image](https://user-images.githubusercontent.com/94042374/203084148-619277a7-1326-4f97-9d65-6f1ac1680c33.png)

**Comment by Christabellet** [comment]
Test cases completed

![Image](https://user-images.githubusercontent.com/94042374/203085124-ef2d4215-9c79-4a27-8357-677c6b98203a.png)

**Comment by Christabellet** [comment]
Pseudocode Completed

![Image](https://user-images.githubusercontent.com/94042374/203085660-3d4cbcc9-0612-41d2-973b-88ccb6213690.png)

**Comment by rawsashimi1604** [comment]
updated pseudocode, need to remove exit lines from CFG
![Image](https://user-images.githubusercontent.com/75880261/203511012-704489c6-813f-4885-a108-261682039eb0.png)

**Comment by rawsashimi1604** [comment]
Added test specification


![Image](https://user-images.githubusercontent.com/75880261/204076572-8c2186eb-c11a-464a-af47-4539e4aa8c50.png)

**Comment by rawsashimi1604** [comment]
Added test cases for white box

![Image](https://user-images.githubusercontent.com/75880261/204076579-30fdb5d1-7d2a-4046-9dcc-27d558ca1770.png)


![Image](https://user-images.githubusercontent.com/75880261/204076584-07254949-42dd-4510-958f-6e64fe0bd756.png)



![Image](https://user-images.githubusercontent.com/75880261/204076586-22a46f9d-b3b5-4a61-83da-1a4876e98242.png)

**Comment by rawsashimi1604** [comment]
added psuedocode explaination


![Image](https://user-images.githubusercontent.com/75880261/204076741-f8289f9f-80c0-44fa-a9e6-efdc9e10d1de.png)
