### ISSUE TITLE
M3 - State Transition Diagram

### ISSUE THREAD

**Issue by Christabellet** [rawsashimi1604/ICT2101-2201-P3-Team1#81]
## Complete State Transition Diagram

Start Date: 17/11/2022
End Date: 25/11/2022

### Preconditions:
- None

### Definition of done:
- [x] State transition diagram completed showcasing all state transitions in the system
- [x] Added to the report

**Comment by rawsashimi1604** [comment]
done and added to report
![Image](https://user-images.githubusercontent.com/75880261/204036081-87ae5db6-0c50-4f70-b338-e7d4eb06e8a0.png)
