### ISSUE TITLE
M3 - Project Wireframes

### ISSUE THREAD

**Issue by Christabellet** [rawsashimi1604/ICT2101-2201-P3-Team1#83]
## UI Wireframes for M3
Develop UI Wireframes showcasing the TOMS application for M3

Start Date: 30/10/2022
End Date: 26/11/2022

### Preconditions:
- Requirements are completed

### Definition of done:
- [x] UI Wireframes completed, all features are covered based on the requirement specs
- [x] Added to the report.

**Comment by jibai-kia** [comment]
Here are our project wireframes.
![Image](https://user-images.githubusercontent.com/90103591/204076353-0fac08bd-2793-4480-8e86-5044d6a5710c.png)
![Image](https://user-images.githubusercontent.com/90103591/204076354-fc8fea92-436a-485d-a980-64665b965df7.png)
![Image](https://user-images.githubusercontent.com/90103591/204076367-6f5f89ac-331d-4c32-bbf3-7d427197e4e3.png)
![Image](https://user-images.githubusercontent.com/90103591/204076372-3891fed3-b769-427e-aed3-0b86bc6bd0fa.png)
![Image](https://user-images.githubusercontent.com/90103591/204076351-e84cabfa-3ce4-447e-b8d8-88a8cfff724a.png)
![Image](https://user-images.githubusercontent.com/90103591/204076366-3f1d44d0-6610-4f5c-abc0-5dc54f447266.png)
![Image](https://user-images.githubusercontent.com/90103591/204076368-56020979-734f-4e47-b392-0773278d19f9.png)
![Image](https://user-images.githubusercontent.com/90103591/204076352-0bad5ad4-adc6-4dd7-a464-5e3aa46bd548.png)
![Image](https://user-images.githubusercontent.com/90103591/204076355-fc9dc6f3-0f10-4cf4-8175-db5ccd62d289.png)
![Image](https://user-images.githubusercontent.com/90103591/204076373-10aeccf3-5068-4c68-b4cb-c2cfbc38bf41.png)
![Image](https://user-images.githubusercontent.com/90103591/204076350-e2ee0920-c564-471a-a34e-0a0d38cdb36b.png)
![Image](https://user-images.githubusercontent.com/90103591/204076371-325931e4-cb15-4fe4-b37b-b1177243c6dd.png)
![Image](https://user-images.githubusercontent.com/90103591/204076356-5a32958d-f956-467b-9f16-08aaedaaaf19.png)
![Image](https://user-images.githubusercontent.com/90103591/204076363-ce7e06f5-db01-4b29-8434-c8544d68834b.png)
![Image](https://user-images.githubusercontent.com/90103591/204076362-ac11fb89-c07e-4f1e-a787-69bf6342fef9.png)
![Image](https://user-images.githubusercontent.com/90103591/204076357-c1a47d3c-a41d-4bb5-9581-b4b873dce8a8.png)
![Image](https://user-images.githubusercontent.com/90103591/204076374-a774d09f-46fe-4ff0-b3b1-70d7437fbe27.png)
![Image](https://user-images.githubusercontent.com/90103591/204076360-9940a2ff-6d77-46f0-bed3-c1abf742f6f2.png)
![Image](https://user-images.githubusercontent.com/90103591/204076359-df05e68a-f648-4d72-8ea9-0301e4e4cdbc.png)
![Image](https://user-images.githubusercontent.com/90103591/204076358-b5daf252-6f0b-4ab5-a4d8-dfe649daae61.png)
![Image](https://user-images.githubusercontent.com/90103591/204076361-32f396d5-0747-4401-b4bb-08e79d0f1188.png)
![Image](https://user-images.githubusercontent.com/90103591/204076378-60739d91-666f-458a-99e5-c1d92ef0a5ea.png)
![Image](https://user-images.githubusercontent.com/90103591/204076376-0d52675e-b28f-4f73-a80a-276a6865456f.png)
![Image](https://user-images.githubusercontent.com/90103591/204076369-445e0e8c-4ac4-464c-bece-e2514bfd7f05.png)
![Image](https://user-images.githubusercontent.com/90103591/204076365-9f48bd7b-281f-4f79-a724-c6048a89df9d.png)
![Image](https://user-images.githubusercontent.com/90103591/204076370-d783ed40-c930-4632-a5d2-290a6177c241.png)
![Image](https://user-images.githubusercontent.com/90103591/204076364-442c342d-e443-441b-a9b4-dd9b605ac2ae.png)
![Image](https://user-images.githubusercontent.com/90103591/204076377-c892e2a0-4d3c-4d75-967f-d705a72719b0.png)
![Image](https://user-images.githubusercontent.com/90103591/204076375-ccbeb101-b1f0-4853-bdf3-784d08f42841.png)
