### ISSUE TITLE
M3 - Project Management

### ISSUE THREAD

**Issue by Christabellet** [rawsashimi1604/ICT2101-2201-P3-Team1#84]
## Project Management for M3
Project management resources for M3. 

Start Date: 30/10/2022
End Date: 26/11/2022

### Preconditions:
- None

### Definition of done:
- [x] Github Issues are completed, added to board with appropriate descriptions
- [x] Gannt Chart done.
- [x] Burndown Chart done.
- [x] Added to report.

**Comment by rawsashimi1604** [comment]
![Image](https://user-images.githubusercontent.com/75880261/202963612-f044328a-517d-4fda-b908-48282323c9c8.png)

Completed adding Github issues to the board, and their descriptions

**Comment by rawsashimi1604** [comment]
Added Burndown Chart


![Image](https://user-images.githubusercontent.com/75880261/204079996-4cfad246-cb6a-47e6-b6ec-b82eeb68f1c6.png)

**Comment by jibai-kia** [comment]
Here's the Gantt Chart

![Image](https://user-images.githubusercontent.com/90103591/204080060-09733140-5e20-4d82-9425-eb9bc64f5642.png)
