### ISSUE TITLE
M3 - Product Scope

### ISSUE THREAD

**Issue by Christabellet** [rawsashimi1604/ICT2101-2201-P3-Team1#85]
## Report Introduction for M3
Complete the introduction section for M3 Report.

Start Date: 17/11/2022
End Date: 17/11/2022

### Preconditions:
- None

### Definition of done:
- [x] Section 1.1 Product Scope done
- [x] Section 1.2 Intended Audience and Overview done
- [x] Section 1.3 References and Acknowledgements done

**Comment by irfaan96** [comment]
Completed Section 1

![Image](https://user-images.githubusercontent.com/33274365/204078610-1537d104-7aaf-4da9-bb41-d28b3d2d1240.png)
