### ISSUE TITLE
M3 - Black Box Testing

### ISSUE THREAD

**Issue by irfaan96** [rawsashimi1604/ICT2101-2201-P3-Team1#89]
## Complete Black Box Testing for M3

Start Date: 17/11/2022
End Date: 26/11/2022

### Preconditions:
- State transition diagram has been completed

### Definition of done:
- [x] All state transitions are covered
- [x] At least 1 decision table, boundary analysis or equivalence partitioning per state transition completed
- [x] Added to the report

**Comment by rawsashimi1604** [comment]
All tests completed
![Image](https://user-images.githubusercontent.com/75880261/204074466-05929ddf-1452-4516-a51b-8b5204ff8b17.png)
