### ISSUE TITLE
M3 - Update Specific Requirements

### ISSUE THREAD

**Issue by irfaan96** [rawsashimi1604/ICT2101-2201-P3-Team1#90]
## Update Specific Requirements for the Report
Complete Section 2 of the report, updating requirements changes if needed.

Start Date: - 17/11/2022
End Date: - 17/11/2022

### Preconditions:
- None

### Definition of done:
- [x] Added to the report.

**Comment by jibai-kia** [comment]
Here's the removed Specific Requirements
![Image](https://user-images.githubusercontent.com/90103591/204076597-df38111e-ae6c-4b7d-8fa8-040dd96bf5f4.png)

Here's the updated Specific Requirements
![Image](https://user-images.githubusercontent.com/90103591/204076622-b09c5587-4064-44be-a351-489bb97d540c.png)
![Image](https://user-images.githubusercontent.com/90103591/204076630-2cbf33ca-c3c3-4d6d-8452-2cf5bcedb306.png)
