### ISSUE TITLE
M3 - Individual Reflections

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2101-2201-P3-Team1#91]
## Individual Reflections for M3
Individual Members Task Reflections

Start Date: 26/11/2022
End Date: 26/11/2022

### Preconditions:
- Main body of M3 completed

### Definition of done:
- [x] Christabelle's reflection added to the report
- [x] Irfaan's reflection added to the report
- [x] Yong Chong's reflection added to the report
- [x] Gavin's reflection added to the report

**Comment by jibai-kia** [comment]
Here is my reflection

![Image](https://user-images.githubusercontent.com/90103591/204076494-4c98e248-11ea-4f2c-a348-0312ef55f1bc.png)

**Comment by rawsashimi1604** [comment]
Reflection done
![Image](https://user-images.githubusercontent.com/75880261/204077148-76891c38-4b75-4157-b477-0e3c1dbcce80.png)

**Comment by irfaan96** [comment]
Added my reflections

![Image](https://user-images.githubusercontent.com/33274365/204077614-97ef8230-3685-4f81-af63-cea6a4901e3c.png)

**Comment by Christabellet** [comment]
Reflection completed

![Image](https://user-images.githubusercontent.com/94042374/204099277-31962a4c-723f-4b2e-8a44-493467d39f3f.png)
